# Generated by Django 5.2.1 on 2025-05-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengeresult',
            name='submitted_at',
        ),
    ]
